name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: Check quality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['type-check', 'format:check', 'build:lib', 'build']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run command
        run: pnpm run ${{ matrix.command }}
        continue-on-error: ${{ matrix.command == 'build:lib' }}

      - name: Check library bundle size
        if: matrix.command == 'build:lib'
        uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'build:lib'
          pattern: './dist/**/*.{js,mjs,css}'
          exclude: '{**/*.map,**/node_modules/**}'
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Check demo app bundle size
        if: matrix.command == 'build'
        uses: preactjs/compressed-size-action@v2
        with:
          build-script: 'build'
          pattern: './build/static/**/*.{js,css}'
          exclude: '{**/*.map,**/node_modules/**}'
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
